# Generated by Django 4.0.3 on 2022-05-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_postions_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
