# Generated by Django 4.0.3 on 2022-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_positions_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='color',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='projectparticipants',
            name='kicked_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='closed_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
