# Generated by Django 4.0.3 on 2022-05-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_positions_color_alter_positions_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
