# Generated by Django 4.0.3 on 2022-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_positions_project_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='icon_url',
            field=models.TextField(blank=True),
        ),
    ]
