# Generated by Django 4.0.3 on 2022-05-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projects_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='creator',
        ),
    ]
