# Generated by Django 4.0.3 on 2022-05-27 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_alter_positions_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='projectparticipants',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
