# Generated by Django 4.0.3 on 2022-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_projects_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='invited_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectparticipants',
            name='kicked_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateField(),
        ),
    ]
