# Generated by Django 4.0.3 on 2022-11-12 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_projects_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='projects',
            name='icon',
            field=models.ImageField(null=True, upload_to=src.base.services.get_path_upload_project_icon, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), src.base.services.validate_size_image]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to=src.base.services.get_path_upload_project_files, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt, doc, docx, pdf, xlsx'])], verbose_name='Файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='ник')),
                ('estimation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
