# Generated by Django 4.0.3 on 2022-11-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_projects_icon_url_projects_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectfeedback',
            name='estimation',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfeedback',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
            preserve_default=False,
        ),
    ]
