version: '3.3'

services:
  db:
    image: postgres:14-alpine
    container_name: WebStudio_postgres
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - dev.env

  server:
    build: ./server
    container_name: server
    command: bash entrypoint.sh
    volumes:
      - ./server/src/users/migrations:/server/src/users/migrations
      - ./server/src/boards/migrations:/server/src/boards/migrations
      - ./server/src/projects/migrations:/server/src/projects/migrations
    ports:
      - 8001:8001
    networks:
      - default
    env_file:
      - server/dev.env
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:



