version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: WebStudio_postgres
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env

  server:
    build: ./
    container_name: server
    command: bash entrypoint.sh
    volumes:
      - ./src/users/migrations:/server/src/users/migrations
      - ./src/boards/migrations:/server/src/boards/migrations
      - ./src/projects/migrations:/server/src/projects/migrations
    ports:
      - 8000:8000
    networks:
      - default
    env_file:
      - server/.env
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:



