version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build:
      context: ./WebStudio
      dockerfile: Dockerfile
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - default
    env_file:
      - .env
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:




