# Generated by Django 4.0.3 on 2022-05-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_boardcolumns_title_alter_boards_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='boards.tasktags'),
        ),
    ]
