# Generated by Django 4.0.3 on 2022-05-19 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_alter_tasks_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='board',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='boards.boards'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='executor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL),
        ),
    ]
