# Generated by Django 4.0.3 on 2022-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(default='работяга', max_length=64, unique=True, verbose_name='название'),
        ),
    ]
