# Generated by Django 4.0.3 on 2022-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время заморозки'),
        ),
    ]
