# Generated by Django 4.0.3 on 2022-05-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usercontact_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='UserRole',
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
