# Generated by Django 4.0.3 on 2022-05-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_positions_project'),
        ('users', '0007_rename_role_userrole_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.positions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
    ]
