# Generated by Django 4.0.3 on 2022-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_disabled_at_alter_user_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Дизайнер', 'designer'), ('Бэк', 'backend'), ('Фронт', 'frontend'), ('Менеджер', 'manager')], max_length=25, null=True),
        ),
    ]
