# Generated by Django 4.0.3 on 2022-11-12 09:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_post_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=src.base.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), src.base.services.validate_size_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Дизайнер', 'designer'), ('Бэк', 'backend'), ('Фронт', 'frontend'), ('Менеджер', 'manager')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userrole'),
        ),
    ]
